# Generated by Django 4.2.7 on 2025-03-08 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tryout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='contoh: Tryout UAS DDP2\n', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character\n')])),
                ('subject', models.CharField(help_text='contoh: DDP2\n', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')])),
                ('maximum_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(100, message='Minimal nilainya 100 lah pak')])),
            ],
        ),
    ]
